services:
  pgbackups3:
    image: "ghcr.io/wottpal/pg-backup-s3:main"
    # To not start anything but run the ./backup.sh via Coolify-managed cron
    command: "tail -f /dev/null"
    stdin_open: true
    tty: true
    restart: unless-stopped
    # Environment variables are set via Coolify as well
    environment:
      - "REMOVE_BEFORE=${REMOVE_BEFORE}"
      - "SCHEDULE=${SCHEDULE}"
      - "S3_ENDPOINT=${S3_ENDPOINT}"
      - "S3_REGION=${S3_REGION}"
      - "S3_ACCESS_KEY_ID=${S3_ACCESS_KEY_ID}"
      - "S3_SECRET_ACCESS_KEY=${S3_SECRET_ACCESS_KEY}"
      - "S3_BUCKET=${S3_BUCKET}"
      - "S3_PREFIX=${S3_PREFIX}"
      - "POSTGRES_BACKUP_ALL=${POSTGRES_BACKUP_ALL}"
      - "POSTGRES_HOST=${POSTGRES_HOST}"
      - "POSTGRES_DATABASE=${POSTGRES_DATABASE}"
      - "POSTGRES_USER=${POSTGRES_USER}"
      - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
      - "POSTGRES_EXTRA_OPTS=${POSTGRES_EXTRA_OPTS}"
